// ─────────────────────────────────────────────────────────────
//  build-css.ts — runs after `tsc` to emit dist/css/theme.css
//  StarUI v1 OKLCH tokens + compat aliases + base utilities.
// ─────────────────────────────────────────────────────────────

import { generateCompatCSS } from '../src/adapters/compatCss';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const FONT_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap');";

const tokens    = readFileSync(resolve(root, 'src/tokens/starui-tokens.css'), 'utf8');
const base      = readFileSync(resolve(root, 'src/styles/base.css'), 'utf8');
const agGrid    = readFileSync(resolve(root, 'src/styles/ag-grid.css'), 'utf8');
const scrollbar = readFileSync(resolve(root, 'src/styles/scrollbar.css'), 'utf8');
const compat    = generateCompatCSS();

const out = [
  '/* @wellsfargo-starui/design-system — StarUI FI unified stylesheet */',
  '/* generated by scripts/build-css.ts; do not edit by hand */',
  '',
  /* @import must be the first statements in the bundled file — PostCSS/Vite reject
     mid-file imports when apps @import this bundle into index.css. */
  FONT_IMPORT,
  '',
  tokens,
  '',
  compat,
  '',
  base,
  '',
  agGrid,
  '',
  scrollbar,
].join('\n');

const outPath = resolve(root, 'dist/css/theme.css');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);

console.log(`✓ wrote ${outPath} (${out.length.toLocaleString()} bytes)`);
