import {
  ModuleRegistry,
  ValidationModule,
  HighlightChangesModule,
  NumberFilterModule,
  TextFilterModule,
  DateFilterModule,
  NumberEditorModule,
  TextEditorModule,
  RowSelectionModule,
  UndoRedoEditModule,
  PaginationModule,
  CsvExportModule,
  CellStyleModule,
  ClientSideRowModelModule,
} from "ag-grid-community";
import {
  ServerSideRowModelModule,
  ServerSideRowModelApiModule,
  RowGroupingModule,
  RowGroupingPanelModule,
  PivotModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  ColumnMenuModule,
  SetFilterModule,
  MultiFilterModule,
  AdvancedFilterModule,
  CellSelectionModule,
  ClipboardModule,
  ContextMenuModule,
  ExcelExportModule,
  MasterDetailModule,
  StatusBarModule,
  TreeDataModule,
  IntegratedChartsModule,
  CalculatedColumnsModule,
  LicenseManager,
} from "ag-grid-enterprise";
import { AgChartsEnterpriseModule } from "ag-charts-enterprise";

ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ServerSideRowModelModule,
  ServerSideRowModelApiModule,
  RowGroupingModule,
  RowGroupingPanelModule,
  PivotModule,
  TreeDataModule,
  CalculatedColumnsModule,
  IntegratedChartsModule.with(AgChartsEnterpriseModule),
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  ColumnMenuModule,
  ContextMenuModule,
  SetFilterModule,
  MultiFilterModule,
  AdvancedFilterModule,
  NumberFilterModule,
  TextFilterModule,
  DateFilterModule,
  NumberEditorModule,
  TextEditorModule,
  RowSelectionModule,
  CellSelectionModule,
  ClipboardModule,
  HighlightChangesModule,
  UndoRedoEditModule,
  PaginationModule,
  CsvExportModule,
  ExcelExportModule,
  MasterDetailModule,
  StatusBarModule,
  CellStyleModule,
  ...(import.meta.env.DEV ? [ValidationModule] : []),
]);

const key = import.meta.env.VITE_AG_GRID_LICENSE as string | undefined;
if (key) LicenseManager.setLicenseKey(key);
