// ─────────────────────────────────────────────────────────────
//  build-css.ts — runs after `tsc` to emit dist/css/theme.css
//  by concatenating base.css + the unified CSS + scrollbar.css.
// ─────────────────────────────────────────────────────────────

import { generateUnifiedCSS } from '../src/adapters/shadcn';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const base      = readFileSync(resolve(root, 'src/styles/base.css'), 'utf8');
const scrollbar = readFileSync(resolve(root, 'src/styles/scrollbar.css'), 'utf8');
const theme     = generateUnifiedCSS();

const out = [
  '/* @starui/design-system — Chroma Desk unified stylesheet */',
  '/* generated by scripts/build-css.ts; do not edit by hand */',
  '',
  base,
  '',
  theme,
  '',
  scrollbar,
].join('\n');

const outPath = resolve(root, 'dist/css/theme.css');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);

console.log(`✓ wrote ${outPath} (${out.length.toLocaleString()} bytes)`);
